### ISSUE TITLE
[Task (Infrastructure)]: Return `IndexerError` instead of `anyhow::Error` from Checkpoint handler in iota-indexer

### ISSUE THREAD

**Issue by tomxey** [iotaledger/iota#1961]
## Description

Created based on https://github.com/iotaledger/iota/pull/1701#discussion_r1721757300

The main change would be to change error type in the Handler trait https://github.com/iotaledger/iota/blob/9ffa8862b510b981647bdd935e56e40feab148c0/crates/iota-indexer/src/framework/interface.rs#L12 from `anyhow::Error` to `IndexerError` and then refactor the rest of the code accordingly.

Consider making use of the new error variant `IndexerError::CheckpointProcessingError` introduced in https://github.com/iotaledger/iota/pull/1701

**Comment by sergiupopescu199** [comment]
@iotaledger/l1-core-infra 

After the re-fork the `Handler` trait [does not longer exist](https://github.com/iotaledger/iota/commit/1bda0fb5c430f29d5c73aca0597f7314db67fd37#diff-8f9a476df16f23b8a88057c98ea937487e3a4719ef2e81a60430e6a120faafe9) and now the `Worker` trait from `iota-data-ingestion-core` crate is replacing the logic, the general issue is that `iota-data-ingestion-core` does not have a dedicated `Error` type but use `anyhow` which is not ideal as it is a crate not an application, I suppose we could create a new issue and close this one as it could include more changes than anticipated because the `Worker` trait is implemented in the following crates:

1. `iota-analytics-indexer`
2. `iota-data-ingestion`
3. `iota-indexer-builder`
4. `iota-indexer`

**Comment by kodemartin** [comment]
> [@iotaledger/l1-core-infra](https://github.com/orgs/iotaledger/teams/l1-core-infra)
> 
> After the re-fork the `Handler` trait [does not longer exist](https://github.com/iotaledger/iota/commit/1bda0fb5c430f29d5c73aca0597f7314db67fd37#diff-8f9a476df16f23b8a88057c98ea937487e3a4719ef2e81a60430e6a120faafe9) and now the `Worker` trait from `iota-data-ingestion-core` crate is replacing the logic, the general issue is that `iota-data-ingestion-core` does not have a dedicated `Error` type but use `anyhow` which is not ideas as it is a crate not an application, I suppose we could create a new issue and close this one as it could include more changes than anticipated because the `Worker` trait is implemented in the following crates:
> 
>     1. `iota-analytics-indexer`
> 
>     2. `iota-data-ingestion`
> 
>     3. `iota-indexer-builder`
> 
>     4. `iota-indexer`

I agree @sergiupopescu199 let's plan a refactoring of `iota-data-ingestion-core` to use a library specific Error type through a new issue.
